@baseUrl = http://localhost:8000/api/v1

GET {{baseUrl}}/tasks

###

GET {{baseUrl}}/tasks/f68e1ac-d5db-4b86-b068-330345bb5c6a

###

POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "name": "Fazer Pão"
}